apiVersion: v1
kind: Secret
metadata:
  name: storageos-secret
type: "kubernetes.io/storageos"
data:
  # set apiAddress to tcp://host:5705. Base64 encode with `echo tcp://myhost:5705 | base64`
  # apiAddress: dGNwOi8vMTI3LjAuMC4xOjU3MDU=
  apiAddress: dGNwOi8vNTIuMTY5LjI4Ljg2OjU3MDU= # tcp://52.169.28.86:5705 - externalip for lb - encoded via bing
  # apiAddress: dGNwOi8vNTIuMTY5LjI4Ljg2OjU3MDUK # tcp://52.169.28.86:5705 - externalip for lb
  # apiAddress: dGNwOi8vMTAuMC4zOS4zMjo1NzA1Cg== # tcp://10.0.39.32:5705 - clusterip for storageos service
  apiUsername: c3RvcmFnZW9z
  apiPassword: c3RvcmFnZW9z

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: storageos-redis
provisioner: kubernetes.io/storageos
parameters:
  pool: default
  description: Kubernetes volume
  fsType: ext4
  adminSecretNamespace: default
  adminSecretName: storageos-secret

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storageos-redis0001
  annotations:
    volume.beta.kubernetes.io/storage-class: storageos-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# redis pod
apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: redis
  name: redis 
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - name: redisport
      containerPort: 6379
    volumeMounts:
        - mountPath: /redis-master-data
          name: redis-data
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: storageos-redis0001

---
# redis service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: redisport

---
# counter pod
apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: counter
  name: counter
spec:
  containers:
  - name: counter
    image: andersjanmyr/counter
    env:
    - name: REDIS_URL
      value: redis:6379
    ports:
    - name: http
      containerPort: 80

---
# redis service
apiVersion: v1
kind: Service
metadata:
  name: counter
spec:
  selector:
    app: counter
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: http